export const moviesFilterButtonsData = [
    { name: 'Все', link: '/' },
    { name: 'Драма', link: '/' },
    { name: 'Военный', link: '/' },
    { name: 'Криминал', link: '/' },
    { name: 'Приключения', link: '/' },
    { name: 'Триллер', link: '/' },
    { name: 'Детектив', link: '/' },
    { name: 'История', link: '/' },
    { name: 'Мелодрама', link: '/' },
    { name: 'Ужасы', link: '/' },
    { name: 'Детский', link: '/' },
    { name: 'Комедия', link: '/' },
    { name: 'Музыка', link: '/' },
    { name: 'Семейный', link: '/' },
    { name: 'Фантастика', link: '/' },
    { name: 'Боевик', link: '/' },
    { name: 'Вестерн', link: '/' },
    { name: 'Документльный', link: '/' },
    { name: 'Фэнтези', link: '/' },
]
